# Generated by Django 4.0.5 on 2022-06-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Aprobado', models.BooleanField(null=True)),
                ('Presupuesto', models.IntegerField(null=True)),
                ('Creado', models.DateTimeField(auto_now_add=True, verbose_name='')),
            ],
        ),
    ]
