# Generated by Django 4.0.5 on 2022-06-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Presupuesto',
            field=models.IntegerField(default=0),
        ),
    ]
